"""Manejo de errores y excepciones personalizadas."""

from .exceptions import (
    ErrorCode,
    ServiceError,
    ValidationError,
    AuthenticationError,
    PermissionError,
    ResourceNotFoundError,
    RateLimitError,
    RateLimitExceeded,
    QuotaExceededError,
    ServiceUnavailableError,
    ExternalApiError,
    DatabaseError,
    CacheError,
    LlmGenerationError,
    ModelNotAvailableError,
    EmbeddingError,
    DocumentProcessingError,
    CollectionError,
    ConversationError,
    AgentNotFoundError,
    AgentInactiveError,
    AgentExecutionError,
    AgentSetupError,
    AgentToolError,
    AgentLimitExceededError,
    InvalidAgentIdError,
    AgentAlreadyExistsError,
    AgentQuotaExceededError,
    QueryProcessingError,
    CollectionNotFoundError,
    RetrievalError,
    GenerationError,
    InvalidQueryParamsError,
    EmbeddingGenerationError,
    EmbeddingModelError,
    TextTooLargeError,
    BatchTooLargeError,
    InvalidEmbeddingParamsError,
    ConfigurationError,
    setup_error_handling
)

__all__ = [
    "ErrorCode",
    "ServiceError",
    "ValidationError",
    "AuthenticationError",
    "PermissionError",
    "ResourceNotFoundError",
    "RateLimitError",
    "RateLimitExceeded",
    "QuotaExceededError",
    "ServiceUnavailableError",
    "ExternalApiError",
    "DatabaseError",
    "CacheError",
    "LlmGenerationError",
    "ModelNotAvailableError",
    "EmbeddingError",
    "DocumentProcessingError",
    "CollectionError",
    "ConversationError",
    "AgentNotFoundError",
    "AgentInactiveError",
    "AgentExecutionError",
    "AgentSetupError",
    "AgentToolError",
    "AgentLimitExceededError",
    "InvalidAgentIdError",
    "AgentAlreadyExistsError",
    "AgentQuotaExceededError",
    "QueryProcessingError",
    "CollectionNotFoundError",
    "RetrievalError",
    "GenerationError",
    "InvalidQueryParamsError",
    "EmbeddingGenerationError",
    "EmbeddingModelError",
    "TextTooLargeError",
    "BatchTooLargeError",
    "InvalidEmbeddingParamsError",
    "ConfigurationError",
    "setup_error_handling"
]

"""
Sistema de manejo de errores para todos los servicios.
"""

from .handlers import (
    setup_error_handling,
    handle_errors,
    handle_service_error_simple,
    handle_service_error_internal,
)

from .responses import (
    create_error_response,
    format_error_response,
    sanitize_content,
)

__all__ = [
    # exceptions
    "ErrorCode",
    "ServiceError",
    "ValidationError",
    "AuthenticationError",
    "PermissionError",
    "ResourceNotFoundError",
    "RateLimitError",
    "RateLimitExceeded",
    "QuotaExceededError",
    "ServiceUnavailableError",
    "ExternalApiError",
    "DatabaseError",
    "CacheError",
    "LlmGenerationError",
    "ModelNotAvailableError",
    "EmbeddingError",
    "DocumentProcessingError",
    "CollectionError",
    "ConversationError",
    "AgentNotFoundError",
    "AgentInactiveError",
    "AgentExecutionError",
    "AgentSetupError",
    "AgentToolError",
    "AgentLimitExceededError",
    "InvalidAgentIdError",
    "AgentAlreadyExistsError",
    "AgentQuotaExceededError",
    "QueryProcessingError",
    "CollectionNotFoundError",
    "RetrievalError",
    "GenerationError",
    "InvalidQueryParamsError",
    "EmbeddingGenerationError",
    "EmbeddingModelError",
    "TextTooLargeError",
    "BatchTooLargeError",
    "InvalidEmbeddingParamsError",
    "ConfigurationError",
    # handlers
    "setup_error_handling",
    "handle_errors",
    "handle_service_error_simple",
    "handle_service_error_internal",
    # responses
    "create_error_response",
    "format_error_response",
    "sanitize_content",
]