version: '3.8'

services:
  supabase:
    build:
      context: ./docker/supabase
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - supabase-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  ollama:
    build:
      context: ./docker/ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      # Montar los scripts para que puedan ser ejecutados manualmente si es necesario
      - ./docker/ollama/scripts:/scripts
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - OLLAMA_LOG_LEVEL=info       # Ajustado para ver más información durante configuración
      - OLLAMA_VERBOSE=false        # Desactivar mensajes detallados
      - CUDA_VISIBLE_DEVICES=0      # Usar la primera GPU (RTX 3090)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always

  embedding-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.embedding
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./common:/app/common
      - ./embedding-service:/app/embedding-service
      - ./logs:/app/logs
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      # Variables de credenciales
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL:-postgresql://postgres:postgres@supabase:5432/nooble3_db}
      - SUPABASE_KEY=${SUPABASE_KEY:-postgres}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-postgres}
      
      # Variables de identificación del servicio
      - SERVICE_NAME=embedding-service
      - DOCKER_CONTAINER=true
      
      # Variables de conexión con servicios
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_API_URL=http://ollama:11434
      
      # Variables de configuración multi-tenant
      - TENANT_ID=default
      - CONFIG_ENVIRONMENT=development
      - LOAD_CONFIG_FROM_SUPABASE=true
      
      # Variables de configuración general
      - LOG_LEVEL=INFO
      - USE_OLLAMA=${USE_OLLAMA:-true}
      - DEFAULT_OLLAMA_EMBEDDING_MODEL=${DEFAULT_OLLAMA_EMBEDDING_MODEL:-nomic-embed-text}
      - DEFAULT_OLLAMA_LLM_MODEL=${DEFAULT_OLLAMA_LLM_MODEL:-qwen3:1.7b}
    depends_on:
      redis:
        condition: service_healthy
      supabase:
        condition: service_healthy
      ollama:
        condition: service_started

  query-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.query
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - ./common:/app/common
      - ./query-service:/app/query-service
      - ./logs:/app/logs
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      # Variables de credenciales
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL:-postgresql://postgres:postgres@supabase:5432/nooble3_db}
      - SUPABASE_KEY=${SUPABASE_KEY:-postgres}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-postgres}
      
      # Variables de identificación del servicio
      - SERVICE_NAME=query-service
      - DOCKER_CONTAINER=true
      
      # Variables de conexión con servicios
      - REDIS_URL=redis://redis:6379/0
      - EMBEDDING_SERVICE_URL=http://embedding-service:8001
      - OLLAMA_API_URL=http://ollama:11434
      
      # Variables de configuración multi-tenant
      - TENANT_ID=default
      - CONFIG_ENVIRONMENT=development
      - LOAD_CONFIG_FROM_SUPABASE=true
      
      # Variables de configuración general
      - LOG_LEVEL=INFO
      - USE_OLLAMA=${USE_OLLAMA:-true}
      - DEFAULT_OLLAMA_EMBEDDING_MODEL=${DEFAULT_OLLAMA_EMBEDDING_MODEL:-nomic-embed-text}
      - DEFAULT_OLLAMA_LLM_MODEL=${DEFAULT_OLLAMA_LLM_MODEL:-qwen3:1.7b}
    depends_on:
      redis:
        condition: service_healthy
      supabase:
        condition: service_healthy
      embedding-service:
        condition: service_started
      ollama:
        condition: service_started

  agent-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.agent
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - ./common:/app/common
      - ./agent-service:/app/agent-service
      - ./logs:/app/logs
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      # Variables de credenciales
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL:-postgresql://postgres:postgres@supabase:5432/nooble3_db}
      - SUPABASE_KEY=${SUPABASE_KEY:-postgres}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-postgres}
      
      # Variables de identificación del servicio
      - SERVICE_NAME=agent-service
      - DOCKER_CONTAINER=true
      
      # Variables de conexión con servicios
      - REDIS_URL=redis://redis:6379/0
      - EMBEDDING_SERVICE_URL=http://embedding-service:8001
      - QUERY_SERVICE_URL=http://query-service:8002
      - OLLAMA_API_URL=http://ollama:11434
      
      # Variables de configuración multi-tenant
      - TENANT_ID=default
      - CONFIG_ENVIRONMENT=development
      - LOAD_CONFIG_FROM_SUPABASE=true
      
      # Variables de configuración general
      - LOG_LEVEL=INFO
      - USE_OLLAMA=${USE_OLLAMA:-true}
      - DEFAULT_OLLAMA_EMBEDDING_MODEL=${DEFAULT_OLLAMA_EMBEDDING_MODEL:-nomic-embed-text}
      - DEFAULT_OLLAMA_LLM_MODEL=${DEFAULT_OLLAMA_LLM_MODEL:-qwen3:1.7b}
      - JOB_LOCK_EXPIRE_SECONDS=600
    depends_on:
      redis:
        condition: service_healthy
      supabase:
        condition: service_healthy
      embedding-service:
        condition: service_started
      query-service:
        condition: service_started
      ollama:
        condition: service_started

  ingestion-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.ingestion
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./common:/app/common
      - ./ingestion-service:/app/ingestion-service
      - ./logs:/app/logs
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      # Variables de credenciales
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL:-postgresql://postgres:postgres@supabase:5432/nooble3_db}
      - SUPABASE_KEY=${SUPABASE_KEY:-postgres}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-postgres}
      
      # Variables de identificación del servicio
      - SERVICE_NAME=ingestion-service
      - DOCKER_CONTAINER=true
      
      # Variables de conexión con servicios
      - REDIS_URL=redis://redis:6379/0
      - EMBEDDING_SERVICE_URL=http://embedding-service:8001
      - QUERY_SERVICE_URL=http://query-service:8002
      - OLLAMA_API_URL=http://ollama:11434
      - JOB_LOCK_EXPIRE_SECONDS=600
      
      # Variables de configuración multi-tenant
      - TENANT_ID=default
      - CONFIG_ENVIRONMENT=development
      - LOAD_CONFIG_FROM_SUPABASE=true
      
      # Variables de configuración general
      - LOG_LEVEL=INFO
      - USE_OLLAMA=${USE_OLLAMA:-true}
      - DEFAULT_OLLAMA_EMBEDDING_MODEL=${DEFAULT_OLLAMA_EMBEDDING_MODEL:-nomic-embed-text}
      - DEFAULT_OLLAMA_LLM_MODEL=${DEFAULT_OLLAMA_LLM_MODEL:-qwen3:1.7b}
    depends_on:
      redis:
        condition: service_healthy
      supabase:
        condition: service_healthy
      embedding-service:
        condition: service_started
      ollama:
        condition: service_started

  worker-service:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.worker
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./common:/app/common
      - ./worker-service:/app/worker-service
      - ./logs:/app/logs
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      # Variables de credenciales
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL:-postgresql://postgres:postgres@supabase:5432/nooble3_db}
      - SUPABASE_KEY=${SUPABASE_KEY:-postgres}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-postgres}
      
      # Variables de identificación del servicio
      - SERVICE_NAME=worker-service
      - DOCKER_CONTAINER=true
      
      # Variables de conexión con servicios
      - REDIS_URL=redis://redis:6379/0
      - EMBEDDING_SERVICE_URL=http://embedding-service:8001
      - QUERY_SERVICE_URL=http://query-service:8002
      - AGENT_SERVICE_URL=http://agent-service:8003
      - INGESTION_SERVICE_URL=http://ingestion-service:8000
      - OLLAMA_API_URL=http://ollama:11434
      - JOB_LOCK_EXPIRE_SECONDS=600
      
      # Variables de configuración multi-tenant
      - TENANT_ID=default
      - CONFIG_ENVIRONMENT=development
      - LOAD_CONFIG_FROM_SUPABASE=true
      
      # Variables de configuración general
      - LOG_LEVEL=INFO
      - MAX_WORKERS=3
    depends_on:
      redis:
        condition: service_healthy
      supabase:
        condition: service_healthy
      embedding-service:
        condition: service_started
      query-service:
        condition: service_started
      agent-service:
        condition: service_started
      ingestion-service:
        condition: service_started

volumes:
  supabase-data:
  redis-data:
  ollama-data:
  logs: