apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  supabase-url: "https://your-supabase-project.supabase.co"
  redis-url: "redis://redis:6379/0"
  embedding-service-url: "http://embedding-service:8001"
  query-service-url: "http://query-service:8002"
  ingestion-service-url: "http://ingestion-service:8004"
  agent-service-url: "http://agent-service:8003"
  log-level: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
type: Opaque
data:
  # Estos valores son placeholders y deben ser reemplazados con valores reales codificados en base64
  # echo -n "your-api-key" | base64
  openai-api-key: b3BlbmFpLWFwaS1rZXktcGxhY2Vob2xkZXI=
  supabase-key: c3VwYWJhc2Uta2V5LXBsYWNlaG9sZGVy=